language: php

php:
  - 5.6

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email: false
