language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

before_install:
    - sh -c "sudo mkdir vendor"
    - sh -c "sudo mount -t tmpfs -o size=512M tmpfs vendor"

install:
    - composer install --prefer-source --no-interaction

before_script:
    - sh -c "sudo mkdir /tmp/Elcodi"
    - sh -c "sudo mount -t tmpfs -o size=512M tmpfs /tmp/Elcodi/"

script:
  - phpunit

notifications:
    email: false
