language: php

php:
  - 5.6

before_install:
  - 'if [[ $TRAVIS_PULL_REQUEST != "false" && $TRAVIS_PHP_VERSION != "7.0" && $TRAVIS_PHP_VERSION != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;'
  - composer self-update

install:
  - 'if [[ $TRAVIS_PULL_REQUEST = "false" ]]; then composer require --no-update satooshi/php-coveralls; fi;'
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - 'if [[ $TRAVIS_PULL_REQUEST = "false" ]]; then php vendor/bin/coveralls; fi;'

notifications:
  email: false
